baseURL: "https://aziz0x00.github.io/"
title: aziz0x00's site
paginate: 10
theme: paper-custom

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  color: 'light'                           # linen, wheat, gray, light
  env: developement # to enable google analytics, opengraph, twitter-cards and schema.
  title: aziz0x00
  description: "just a fellow human"

  # avatar: 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name: "Selam \U0001F44B"
  bio: >
    I'm Aziz. interested in **maths** and knowledge, happened to be involved with **computers**. \

    \

    This site is mostly about interesting stuff I find on the web or elsewhere, between maths talks/lectures, and **general life** advices.

  socialIcons:
    - name: github
      url: "https://github.com/aziz0x00"
    - name: cryptohack
      url: "https://cryptohack.org/user/aeaktt"
    - name: competitive_programing
      url: "https://cses.fi/user/140330"
      title: "CSES - Competitive Programming"
    - name: discord
      url: "https://discordapp.com/channels/@me/621444159135416369"

  mainSections: posts


menu:
  main:
    - name: "{ resources }"
      url: /resources
